In [5]:
import numpy as np
import pandas as pd

In [2]:
A = np.array([[56.0,0.0,4.4,64.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  64. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [19]:
Cal = A.sum(axis=0)
print(cal)                # doing the addition vertically down the column
print(cal.shape)# 4 rows he sirf  wese ye bhi 1,4 hi he 

[ 59.  239.  155.4  72.9]
(4,)


In [16]:
print(cal.reshape(1,4))

[[ 59.  239.  155.4  72.9]]


In [21]:
percentage = 100*A/cal 
percentage

array([[94.91525424,  0.        ,  2.83140283, 87.7914952 ],
       [ 2.03389831, 43.51464435, 33.46203346, 10.9739369 ],
       [ 3.05084746, 56.48535565, 63.70656371,  1.2345679 ]])

In [6]:
df = pd.read_csv(r"C:\Users\mynam\all the files for data science\Linear Regression from CampusX\placement.csv")

In [7]:
df.head()

cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [13]:
df.drop('placed',axis=1).head()  # this show that numpy 0 and pandas 0 are different 

cgpa  placement_exam_marks
0  7.19                  26.0
1  7.46                  38.0
2  7.54                  40.0
3  6.42                   8.0
4  7.23                  17.0